### ISSUE TITLE
NaN mapped to the feature grid

### ISSUE THREAD

**Issue by cbaakman** [DeepRank/DeepRank-Mut#14]
During preprocessing:

```
Traceback (most recent call last):
  File "/deeprank/deeprank/generate/DataGenerator.py", line 1115, in map_features
    gt.GridTools(
  File "/deeprank/deeprank/generate/GridTools.py", line 151, in __init__
    self.create_new_data()
  File "/deeprank/deeprank/generate/GridTools.py", line 171, in create_new_data
    self.add_all_features()
  File "/deeprank/deeprank/generate/GridTools.py", line 254, in add_all_features
    self.hdf5_grid_data(dict_data, 'Feature_%s' % (self.feature_mode))
  File "/deeprank/deeprank/generate/GridTools.py", line 764, in hdf5_grid_data
    GridTools._check_features("%s[%s] from %s" % (data_name, key, str(self.variant)), data)
  File "/deeprank/deeprank/generate/GridTools.py", line 745, in _check_features
    raise ValueError("%s: NaN detected" % name)
ValueError: Feature_ind[coulomb] from /pdb/pdb5mnh.ent:a:153:Aspartate->Asparagine: NaN detected
```

When feature values are NaN, training fails.

```
Traceback (most recent call last):
  File "/deeprank/scripts/learn.py", line 79, in <module>
    neural_net.train(nepoch = epoch_count, divide_trainset=[0.7, 0.2, 0.1], train_batch_size = 5, num_workers=0)
  File "/deeprank/deeprank/learn/NeuralNet.py", line 350, in train
    self._train(index_train, index_valid, index_test,
  File "/deeprank/deeprank/learn/NeuralNet.py", line 635, in _train
    train_loss, self.data['train'] = self._epoch("train-epoch-%d" % epoch,
  File "/deeprank/deeprank/learn/NeuralNet.py", line 773, in _epoch
    for d in data_loader:
  File "/usr/local/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 521, in __next__
    data = self._next_data()
  File "/usr/local/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 561, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/usr/local/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 49, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/usr/local/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 49, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/deeprank/deeprank/learn/DataSet.py", line 290, in __getitem__
    features, target = self.load_one_variant(fname, mol)
  File "/deeprank/deeprank/learn/DataSet.py", line 904, in load_one_variant
    raise ValueError(f'Feature {name} not found in file {fname} for variant '
ValueError
```

**Comment by cbaakman** [comment]
There's a check [here](https://github.com/DeepRank/DeepRank_Mut/blob/dd91ceeedad310d458707b94355ae9d2e737019e/deeprank/generate/GridTools.py#L744) to be sure there are no NaNs. It was confirmed by a test that grid features with NaN do not get added to the preprocessed data. The training error is not reproducible and still a mystery.

**Comment by rgayatri** [comment]
Thanks so much Coos. I am re-running mini jobs with the modifications. I am guessing one certain kind of PDB is the culprit. Let's see.

**Comment by rgayatri** [comment]
NaN issues resolved.
